### ISSUE TITLE
Why encodeURIComponent(value)?

### ISSUE THREAD

**Issue by naicha-gg** [litejs/browser-cookie-lite#4]

**Comment by lauriro** [comment]
Otherwise `cookie("test", "a; expires=-1")` would not set cookie

**Comment by naicha-gg** [comment]
I know, but actually stored cookie is not the consumer's expectation, must use `cookie("get")` to decode, the right of choice is in the hands of the consumer, I think.

**Comment by lauriro** [comment]
By specification cookie-value must be US-ASCII or percent-encoded, so decoding is needed anyway.
